spring.application.name=ruiyi

server.port=80
## 编码方式
service_encoding=utf-8

## MySQL驱动
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://81.70.86.120:8866/ruiyi?characterEncoding=UTF-8&useUnicode=true&serverTimezone=UTC&rewriteBatchedStatements=true
#spring.datasource.url=jdbc:mysql://localhost:8866/ruiyi?characterEncoding=UTF-8&useUnicode=true&serverTimezone=UTC&rewriteBatchedStatements=true
#spring.datasource.url=jdbc:mysql://localhost:3306/ruiyi?characterEncoding=UTF-8&useUnicode=true&serverTimezone=UTC&rewriteBatchedStatements=true
spring.datasource.username=root
spring.datasource.password=Liv88625200@@
spring.datasource.hikari.maximumPoolSize=200
spring.datasource.hikari.minimumIdle=10
spring.datasource.hikari.max-lifetime=55000000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.keepalive-time=30000
server.error.include-message=never
server.error.include-binding-errors=never
spring.web.error.include-stacktrace=never
logging.level.org.springframework.security=DEBUG

#server.servlet.context-path=/
server.servlet.session.timeout=3600
server.servlet.context-parameters.encoding=UTF-8
server.servlet.context-parameters.characterEncoding=UTF-8
server.servlet.context-parameters.contentType=text/html;charset=UTF-8
server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.cookie.path=/

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.tomcat.accesslog.enabled=true
server.tomcat.uri-encoding=UTF-8

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.security.user.name=
spring.security.user.password=

spring.mvc.view.prefix=/
spring.mvc.view.suffix=.jsp
