# DeepSeek
deepseek.api.endpoint=https://api.deepseek.com/chat/completions
deepseek.api.key=sk-b3da8e7f93b34e1b89546281acf8384a

lingxing.api.appid=ak_Qz8AibBiyHlBB
lingxing.api.appsecret=6/pgaqMs0caPnnz9DHfwGA==

#basePath=https://www.szninezero.com/
basePath=http://localhost

getIpUrl=https://toolbox.lingxing.com/api/getIp
apiUrl=https://lingxing.szninezero.com

excelSavePath=D:\\files\\ruiyi\\excel\\
imageTempPath=D:\\files\\ruiyi\\image\\temp\\
declarationImagePath=D:\\files\\ruiyi\\image\\declaration\\
productImagePath=D:\\files\\ruiyi\\image\\product\\

#imageServiceUrl=https://szninezero.com/ryimages/
imageServiceUrl=http://localhost:8080/ryimages/

