# DeepSeek
deepseek.api.endpoint=https://api.deepseek.com/v1/chat/completions
deepseek.api.key=${DEEPSEEK_API_KEY}

lingxing.api.appid=ak_Qz8AibBiyHlBB
lingxing.api.appsecret=6/pgaqMs0caPnnz9DHfwGA==

getIpUrl=https://toolbox.lingxing.com/api/getIp
apiUrl=https://openapi.lingxing.com