package com.liwei.ruiyi.bo;

import lombok.*;
import java.math.BigDecimal;
import java.util.*;

@Data
public class TOrder {
    private String amazonOrderId;
    private Integer sid;
    private String sellerName;
    private String orderStatus;
    private BigDecimal orderTotalAmount;
    private String fulfillmentChannel;
    private String postalCode;
    private Integer isReturn;
    private Integer isMcfOrder;
    private Integer isAssessed;
    private Integer isReplacedOrder;
    private Integer isReplacementOrder;
    private Integer isReturnOrder;
    private String orderTotalCurrencyCode;
    private String salesChannel;
    private String trackingNumber;
    private BigDecimal refundAmount;
    private String purchaseDateLocal;
    private String purchaseDateLocalUtc;
    private String shipmentDate;
    private String shipmentDateUtc;
    private String shipmentDateLocal;
    private String lastUpdateDate;
    private String lastUpdateDateUtc;
    private String postedDate;
    private String postedDateUtc;
    private String purchaseDate;
    private String purchaseDateUtc;
    private String earliestShipDate;
    private String earliestShipDateUtc;
    private String gmtModified;
    private String gmtModifiedUtc;
    private String phone;
    private String name;
    private String address;
    private String buyerEmail;
    private String buyerName;
    private String hideTime;
    private String city;
    private String district;
    private String country;
    private String currency;
    private String icon;
    private Integer isBusinessOrder;
    private Integer isPrime;
    private Integer isPremiumOrder;
    private Integer isPromotion;
    private Integer taxesIncluded;
    private String shipServiceLevel;
    private String shipmentServiceLevelCategory;
    private String taxClassifications;
    private String purchaseOrderNumber;
    private String paymentMethod;
    private String cbaDisplayableShippingLabel;
    private String orderType;
    private String latestShipDate;
    private String earliestDeliveryDate;
    private String latestDeliveryDate;
    private Integer numberOfItemsShipped;
    private Integer numberOfItemsUnshipped;
    private String stateOrRegion;
    private String countryCode;
    private String addressLine1;
    private String addressLine2;
    private String addressLine3;
    private String shippingAddress;
}