package com.liwei.ruiyi.bo;

import lombok.*;
import java.math.BigDecimal;
import java.util.*;

@Data
public class TOrderItem {
    private Long id;
    private String orderId;
    private String asin;
    private Integer quantityOrdered;
    private String sellerSku;
    private String localSku;
    private String localName;
    private String orderStatus;
    private BigDecimal profit;
    private String whType;
    private String title;
    private String asinUrl;
    private Integer sid;
    private String sku;
    private Integer productId;
    private String productName;
    private String picUrl;
    private Long orderItemId;
    private BigDecimal pointsMonetaryValueAmount;
    private Integer quantityShipped;
    private BigDecimal itemPriceAmount;
    private BigDecimal itemPriceAmountEstimated;
    private BigDecimal itemTaxAmount;
    private BigDecimal shippingPriceAmount;
    private BigDecimal shippingTaxAmount;
    private BigDecimal giftWrapPriceAmount;
    private BigDecimal giftWrapTaxAmount;
    private BigDecimal shippingDiscountAmount;
    private BigDecimal codFeeAmount;
    private String promotionIds;
    private BigDecimal shippingDiscountTaxAmount;
    private BigDecimal promotionDiscountAmount;
    private BigDecimal promotionDiscountTaxAmount;
    private BigDecimal codFeeDiscountAmount;
    private String giftMessageText;
    private String buyerCustomizedInfo;
    private String isBuyerRequestedCancel;
    private String buyerCancelReason;
    private String giftWrapLevel;
    private String conditionNote;
    private String conditionId;
    private String conditionSubtypeId;
    private String scheduledDeliveryStartDate;
    private String scheduledDeliveryEndDate;
    private String priceDesignation;
    private BigDecimal cgPrice;
    private String feeName;
    private BigDecimal cgTransportCosts;
    private BigDecimal fbaShipmentAmount;
    private BigDecimal fbaShipmentAmountEstimated;
    private BigDecimal commissionAmount;
    private BigDecimal commissionAmountEstimated;
    private BigDecimal otherAmount;
    private String feeCurrency;
    private String feeIcon;
    private BigDecimal feeCostAmount;
    private BigDecimal feeCost;
    private BigDecimal salesPriceAmount;
    private BigDecimal unitPriceAmount;
    private BigDecimal taxAmount;
    private BigDecimal itemTaxAmountEstimated;
    private BigDecimal promotionAmount;
    private BigDecimal itemDiscount;
}